/*!CK:2502917080!*//*1428399472,*/

if (self.CavalryLogger) { CavalryLogger.start_js(["e6Hus"]); }

__d("AdsInsightsSummaryLabels",[],function(a,b,c,d,e,f){b.__markCompiled&&b.__markCompiled();e.exports={};},null);
__d("AttachmentCTA",["Style"],function(a,b,c,d,e,f,g){b.__markCompiled&&b.__markCompiled();var h=10,i={init:function(j){var k=j.parentNode,l=Math.max(k.scrollHeight-j.scrollHeight-h*2,0);g.set(j,'margin-top',l+'px');}};e.exports=i;},null);
__d("AbstractActionList.react",["React","ReactChildren"],function(a,b,c,d,e,f,g,h){b.__markCompiled&&b.__markCompiled();var i=' \u00b7 ',j=g.createClass({displayName:"AbstractActionList",render:function(){var k=true,l=h.map(this.props.children,function(m){if(!m)return m;if(k){k=false;return m;}return {BULLET:i,child:m};});return g.createElement("div",g.__spread({},this.props),l);}});e.exports=j;},null);
__d("ActionList.react",["AbstractActionList.react","joinClasses","React"],function(a,b,c,d,e,f,g,h,i){b.__markCompiled&&b.__markCompiled();var j=i.createClass({displayName:"ActionList",render:function(){return (i.createElement(g,i.__spread({},this.props,{className:h(this.props.className,"fsm fwn fcg")}),this.props.children));}});e.exports=j;},null);
__d("XUIBlock",["React","cx"],function(a,b,c,d,e,f,g,h){b.__markCompiled&&b.__markCompiled();var i=g,j=i.PropTypes,k={propTypes:{background:j.oneOf(['base-wash','light-wash','white','highlight','transparent'])},getDefaultProps:function(){return {background:'transparent'};},getBackgroundClass:function(l){var m=((l.background==='base-wash'?"_4-u5":'')+(l.background==='light-wash'?' '+"_57d8":'')+(l.background==='white'?' '+"_4-u8":'')+(l.background==='highlight'?' '+"_4-u7":''));return m;}};e.exports=k;},null);
__d("XUICard.react",["React","XUIBlock","cx","joinClasses"],function(a,b,c,d,e,f,g,h,i,j){b.__markCompiled&&b.__markCompiled();var k=g.createClass({displayName:"XUICard",propTypes:h.propTypes,getDefaultProps:h.getDefaultProps,render:function(){var l=j("_4-u2",h.getBackgroundClass(this.props));return (g.createElement("div",g.__spread({},this.props,{className:j(this.props.className,l)}),this.props.children));}});e.exports=k;},null);
__d("XUICardSection.react",["React","XUIBlock","cx","joinClasses"],function(a,b,c,d,e,f,g,h,i,j){b.__markCompiled&&b.__markCompiled();'use strict';var k=g.createClass({displayName:"XUICardSection",propTypes:h.propTypes,getDefaultProps:h.getDefaultProps,render:function(){var l=j("_4-u3",h.getBackgroundClass(this.props));return (g.createElement("div",g.__spread({},this.props,{className:j(this.props.className,l)}),this.props.children));}});e.exports=k;},null);
__d("AbstractCheckboxInput.react",["React","cx","invariant","joinClasses"],function(a,b,c,d,e,f,g,h,i,j){b.__markCompiled&&b.__markCompiled();var k=g,l=k.PropTypes,m=g.createClass({displayName:"AbstractCheckboxInput",propTypes:{tooltip:l.string},render:function(){i(!this.props.children||this.props.children.length===0);var n=j(this.props.className,"_kv1"),o=g.createElement("input",g.__spread({},this.props,{className:null,type:"checkbox"}),undefined);return (g.createElement("label",{className:n},o,g.createElement("span",{"data-hover":this.props.tooltip?'tooltip':null,"aria-label":this.props.tooltip})));}});e.exports=m;},null);
__d("XUICheckboxInput.react",["AbstractCheckboxInput.react","React","cx","joinClasses"],function(a,b,c,d,e,f,g,h,i,j){b.__markCompiled&&b.__markCompiled();var k=h.createClass({displayName:"XUICheckboxInput",render:function(){return (h.createElement(g,h.__spread({},this.props,{className:j(this.props.className,"_55sg")}),(void 0)));}});e.exports=k;},null);
__d("XUIDialogSaveButton.react",["React","XUIDialogButton.react","fbt"],function(a,b,c,d,e,f,g,h,i){b.__markCompiled&&b.__markCompiled();var j=g.createClass({displayName:"XUIDialogSaveButton",render:function(){return (g.createElement(h,g.__spread({},this.props,{action:"confirm",label:i._("\u5132\u5b58")})));}});e.exports=j;},null);
__d("GiftCredits",["AsyncRequest","Dialog","URI"],function(a,b,c,d,e,f,g,h,i){b.__markCompiled&&b.__markCompiled();var j={dialog:null,callback:null,purchaseLock:false,purchaseLockExpiryThreshold:5000,purchaseLockTimeoutId:null,getPurchaseCreditPrompt:function(k,l,m,n){j.main(k,null,null,null,m,null,null,null,'BuyCredits',{},n);},redeemGiftcard:function(k,l,m){var n=i(document.location).setPath('/giftcards').toString();j.main(k,null,null,n,null,null,null,null,l,{},m);},getPrompt:function(k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,aa,ba,ca,da,ea,fa,ga,ha){j.main(k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,aa,ba,ca,da,ea,fa,ga,ha);},main:function(k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,aa,ba,ca,da,ea,fa,ga,ha){if(j.isPurchaseLocked())return false;j.setPurchaseLock(true);var ia={_path:'pay',method:'pay',display:'async',app_id:k,receiver:l,api_key:q,credits_purchase:x,action:s,next:n,dev_purchase_params:JSON.stringify(t),additional_params:JSON.stringify(u),order_info:JSON.stringify(m),product:v,package_id:w,request_id:y,sdk:z,quantity:aa,quantity_min:ba,quantity_max:ca,test_currency:da,pricepoint_id:ea,user:fa,user_hash:ga,ingame_gift_data:ha},ja=new g().setURI('/fbml/ajax/dialog/').setData(ia).setMethod('GET').setReadOnly(true).setStatusElement('commerce_get_more_loading');j.callback=o;j.dialog=new h().setAsync(ja).setModal(true).setCloseHandler(function(ka){j.setPurchaseLock(false);o(ka);}).show();},isPurchaseLocked:function(){return j.purchaseLock;},setPurchaseLock:function(k){j.purchaseLock=k;if(k){j.purchaseLockTimeoutId=setTimeout(function(){j.setPurchaseLock(false);},j.purchaseLockExpiryThreshold);}else clearTimeout(j.purchaseLockTimeoutId);return true;}};e.exports=j;},null);
__d("legacy:giftcredits",["GiftCredits"],function(a,b,c,d){b.__markCompiled&&b.__markCompiled();a.GiftCredits=b('GiftCredits');},3);
__d("CanvasResizer",["createArrayFromMixed","CSS","DOMEventListener","Vector"],function(a,b,c,d,e,f,g,h,i,j){b.__markCompiled&&b.__markCompiled();var k;function l(){var n,o=document.documentElement;if(window.innerHeight){n=window.innerHeight;}else if(o&&o.clientHeight){n=o.clientHeight;}else n=document.body.clientHeight;for(var p=0;p<k.length;p++){var q=k[p];if(!h.hasClass(q,'noresize')){var r=j.getElementPosition(q,'document').y,s=n-r;q.style.height=s/(k.length-p)+'px';}}}i.add(window,'resize',l);var m={smartSizingFrameAdded:function(){k=[];var n=g(document.getElementsByTagName('iframe'));n.forEach(function(o){if(h.hasClass(o,'smart_sizing_iframe')&&!h.hasClass(o,'noresize')){h.removeClass(o,'canvas_iframe_util');k.push(o);}});l();}};e.exports=m;},null);
__d("XBoostedPostCalculateBudgetsController",["XController"],function(a,b,c,d,e,f){b.__markCompiled&&b.__markCompiled();e.exports=b("XController").create("\/ads\/ajax\/boosted_post\/calculate_budget\/",{id:{type:"Int",required:true},page_id:{type:"Int",required:true},post_id:{type:"Int"},boosted_post_config:{type:"String",required:true},mode:{type:"Enum",required:true,enumType:1},is_custom_budget:{type:"Bool",defaultValue:false},format_reach:{type:"Bool",defaultValue:false},compress_reach:{type:"Bool",defaultValue:false}});},null);